twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
      pathToWeb: "file:///c:/xampp/htdocs/project/BraiseDoree/public"
